# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(workspace: "RocketDemo.xcworkspace", scheme: "RocketDemo")
    upload_to_app_store
  end

  lane :beta do 
    #build 版本号自动增1，使用fastlane 自带Action 
    
    #指定工作目录下当前工程
    build_app(workspace: "RocketDemo.xcworkspace", scheme: "RocketDemo")
    #上传testflight，会使用fastlane的缓存配置，里面有上传账号的信息
    # upload_to_testflight
    #将自增的版本号代码，上传到github仓库
    # push_git
  end
end
